language: python

sudo: false

matrix:
    include:
        - python: 2.7
          env: TOXENV=cover
        - python: 3.6
          env: TOXENV=cover3
        - python: 3.6
          env: TOXENV=docs
        - python: 2.7
          env: TOXENV=py27
        - python: 3.4
          env: TOXENV=py34
        - python: 3.5
          env: TOXENV=py35
        - python: 3.6
          env: TOXENV=py36

install:
    - travis_retry pip install virtualenv tox pexpect flake8

script:
    - travis_retry tox
